# Generated by Django 5.2 on 2025-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tombamento',
            field=models.IntegerField(),
        ),
    ]
