# Generated by Django 5.2 on 2025-04-28 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logequipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logequipamento',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.equipment'),
        ),
    ]
