# Generated by Django 5.2 on 2025-05-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_logequipamento_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serialnumber',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tombamento',
            field=models.IntegerField(unique=True),
        ),
    ]
