# Generated by Django 5.2 on 2025-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_equipment_serialnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tombamento',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
