# Generated by Django 5.2 on 2025-08-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_equipment_tombamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
