# Generated by Django 5.2 on 2025-08-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipment_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sem_tombamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estoque'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tombamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
