# Generated by Django 5.2 on 2026-06-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_equipment_sem_tombamento_alter_equipment_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='serialnumber',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='tombamento',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
