services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: django_dev
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    env_file:
      - ./.env  # Use um arquivo de ambiente específico se desejar
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env  # Pode ser o mesmo ou um específico para dev
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./controle-estoque
      dockerfile: Dockerfile.dev
    container_name: react_dev
    volumes:
      - ./controle-estoque:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300

    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - web
    restart: always
